# Generated by Django 3.1.3 on 2020-11-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TonersManagement', '0002_auto_20201123_2047'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='toner',
            unique_together={('description', 'color', 'toners_type')},
        ),
    ]
