# Generated by Django 3.1.3 on 2020-11-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TonersManagement', '0003_auto_20201124_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toner',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
    ]
