# Generated by Django 3.1.3 on 2020-12-29 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TonersManagement', '0005_auto_20201228_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcard',
            name='ending_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='simcard',
            name='serial_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
