# Generated by Django 3.1.3 on 2020-12-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TonersManagement', '0006_auto_20201229_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simcard',
            old_name='serial_number',
            new_name='seriel_number',
        ),
    ]
