# Generated by Django 3.1.3 on 2021-01-03 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TonersManagement', '0008_releasevoucher_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriel_number', models.CharField(max_length=30)),
                ('inventory_number', models.CharField(max_length=20)),
                ('device', models.CharField(choices=[('LAPTOP', 'LAPTOP'), ('PC FIX', 'PC FIX'), ('ECRAN', 'ECRAN'), ('IMPRIMANTE', 'IMPRIMANTE')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=30)),
                ('discharge_number', models.CharField(blank=True, max_length=30)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('bill_number', models.CharField(blank=True, max_length=30)),
                ('release_voucher', models.CharField(blank=True, max_length=30)),
                ('buying_date', models.DateField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TonersManagement.customer')),
            ],
        ),
    ]
